### ISSUE TITLE
Extract the resources (.rsrc section) from PE file

### ISSUE THREAD

**Issue by bonigarcia** [zed-0xff/pedump#44]
I want to extract the resources (`.rsrc` section) from the following [PE file](https://drive.google.com/file/d/1V588Pvr5b2uL73yD9pnwGv8C9AGA2Hlc/view?usp=sharing) (152.8 MB). I tried to use pedump for that aim, but no luck yet.

Is it possible?

Any clue on this is greatly appreciated.

For the record, I got that file from the [Edge MSI installer](https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/0a8155d6-0937-4937-8712-1930f09598eb/MicrosoftEdgeEnterpriseX64.msi) (inside the `Binary.MicrosoftEdgeInstaller` stream).

**Comment by zed-0xff** [comment]
```
        --extract ID                 Extract a resource/section/data_dir
                                     ID: datadir:EXPORT     - datadir by type
                                     ID: resource:0x98478   - resource by offset
                                     ID: resource:ICON/#1   - resource by type & name
                                     ID: section:.text      - section by name
                                     ID: section:rva/0x1000 - section by RVA
                                     ID: section:raw/0x400  - section by RAW_PTR
```

did you tried `pedump --extract section:.rsrc --format bin > rsrc.bin` ?

**Comment by bonigarcia** [comment]
I get the following:

```
C:\Users\boni\Downloads>pedump MicrosoftEdge_X64_116.0.1938.76.exe --extract section:.rsrc --format bin > rsrc.bin
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/pedump-0.6.6/lib/pedump/cli.rb:914:in `copy_stream': pread() not implemented (NotImplementedError)
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/pedump-0.6.6/lib/pedump/cli.rb:914:in `extract_section'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/pedump-0.6.6/lib/pedump/cli.rb:854:in `extract'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/pedump-0.6.6/lib/pedump/cli.rb:339:in `dump_action'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/pedump-0.6.6/lib/pedump/cli.rb:163:in `block (3 levels) in run'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/pedump-0.6.6/lib/pedump/cli.rb:158:in `each'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/pedump-0.6.6/lib/pedump/cli.rb:158:in `block (2 levels) in run'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/pedump-0.6.6/lib/pedump/cli.rb:153:in `open'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/pedump-0.6.6/lib/pedump/cli.rb:153:in `block in run'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/pedump-0.6.6/lib/pedump/cli.rb:148:in `each'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/pedump-0.6.6/lib/pedump/cli.rb:148:in `each_with_index'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/pedump-0.6.6/lib/pedump/cli.rb:148:in `run'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/pedump-0.6.6/bin/pedump:7:in `<top (required)>'
        from C:/tools/ruby31/bin/pedump:32:in `load'
        from C:/tools/ruby31/bin/pedump:32:in `<main>'
```

**Comment by zed-0xff** [comment]
added workaround for [IO.pread() not available on windows](https://redmine.ruby-lang.org/issues/12280)
please check with pedump `0.6.7` gem
